### ISSUE TITLE
the pool does not have any blocks found and there are no payment transactions

### ISSUE THREAD

**Issue by sergeyvad** [turtlecoin/turtle-pool#33]
After an emergency power failure, I started the pool, but the pool does not have any blocks found and there are no payment transactions. What's happening?
Found that the api module (node init.js -module=api) makes the database file a small size (dump.rdb).
What could be the problem?

**Comment by funkypenguin** [comment]
Sounds like you might have lost your Redis data.. did you have AOF enabled?

--

**Comment by sergeyvad** [comment]
# redis-cli info persistence
# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1535542010
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

**Comment by sergeyvad** [comment]
I have a database file before it is reduced. I can resuscitate database file?

**Comment by sergeyvad** [comment]
when I redis-cli save -> OK, and the database file is still large.

**Comment by sergeyvad** [comment]
after the start of the pool (node init.js -module=api) changes the size .rdb
`14         14.23M   1       0       55 (+1)             4
14         14.23M   1       0       56 (+1)             4
14         14.23M   1       0       57 (+1)             4
14         14.23M   1       0       58 (+1)             4
13         917.61K  3       0       76 (+18)            6
13         877.62K  3       0       77 (+1)             6
13         877.62K  3       0       78 (+1)             6
13         877.62K  3       0       79 (+1)             6
`

**Comment by sergeyvad** [comment]
`[root@localhost pool]# redis-cli --bigkeys

# Scanning the entire keyspace to find biggest keys as well as
# average sizes per key type.  You can use -i 0.1 to sleep 0.1 sec
# per 100 SCAN commands (not usually needed).

[00.00%] Biggest hash   found so far 'turtlecoin:status:daemon' with 5 fields
[00.00%] Biggest string found so far 'turtlecoin:charts:hashrate:TRTLv11xp99ZGFb3PNRehtHohGyzZkqoU3VpVFvUgeaGhZuUAKnyp63X9eAKSfmmQ5AeZKVKz3r3jEMHMzhtTBkW941fH6QnFpB' with 19 bytes
[00.00%] Biggest string found so far 'turtlecoin:charts:hashrate:TRTLv1Hqo3wHdqLRXuCyX3MwvzKyxzwXeBtycnkDy8ceFp4E23bm3P467xLEbUusH6Q1mqQUBiYwJ2yULJbvr5nKe8kcyc4uyps+unknown' with 901 bytes
[00.00%] Biggest zset   found so far 'turtlecoin:hashrate' with 58923 members
[76.92%] Biggest string found so far 'turtlecoin:charts:hashrate' with 941 bytes
[76.92%] Biggest string found so far 'turtlecoin:charts:difficulty' with 1301 bytes

-------- summary -------

Sampled 13 keys in the keyspace!
Total key length in bytes is 932 (avg len 71.69)

Biggest string found 'turtlecoin:charts:difficulty' has 1301 bytes
Biggest   hash found 'turtlecoin:status:daemon' has 5 fields
Biggest   zset found 'turtlecoin:hashrate' has 58923 members

7 strings with 4929 bytes (53.85% of keys, avg size 704.14)
0 lists with 0 items (00.00% of keys, avg size 0.00)
0 sets with 0 members (00.00% of keys, avg size 0.00)
5 hashs with 18 fields (38.46% of keys, avg size 3.60)
1 zsets with 58923 members (07.69% of keys, avg size 58923.00)
0 streams with 0 entries (00.00% of keys, avg size 0.00)`

**Comment by sergeyvad** [comment]
close or delete issue. I'm using the wrong rdb

**Comment by brandonlehmann** [comment]
Closing at user request
