### ISSUE TITLE
cant npm update?

### ISSUE THREAD

**Issue by Franzferdinan51** [turtlecoin/turtle-pool#37]
so when trying to install i keep running into this error and cannot get past it ive exhausted my knowledge base trying to fix it and require assistance please  :+1: 

> cryptonote-util@0.0.1 install /home/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:121: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pool/node_modules/cryptonote-util
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-13T04_22_06_225Z-debug.log
root@ubuntu:/home/pool#

**Comment by brandonlehmann** [comment]
What OS? Version? Node version?

**Comment by crappyrules** [comment]
looks like `gyp ERR! node -v v10.10.0` and `root@ubuntu`

**Comment by Franzferdinan51** [comment]
ubuntu 18.04.1 node version 10.10 sirs

**Comment by brandonlehmann** [comment]
Update your out of support Node version. That 10.x series has security holes galore.

**Comment by crappyrules** [comment]
@Franzferdinan51 try this out.  I'm sure someone will update this repo, but I was able to get this working properly on Debian 9 and Ubuntu 14 as well.  Should work for you.  https://github.com/crappyrules/turtle-pool

**Comment by Franzferdinan51** [comment]
> Update your out of support Node version. That 10.x series has security holes galore 


what version do u recommend?

**Comment by Franzferdinan51** [comment]
> @Franzferdinan51 try this out. I'm sure someone will update this repo, but I was able to get this working properly on Debian 9 and Ubuntu 14 as well. Should work for you. https://github.com/crappyrules/turtle-pool

ill give it a look sir ty very much

**Comment by brandonlehmann** [comment]
@Franzferdinan51 I meant 0.10 not 10.x (sorry) but I do see you're running 0.10...

Check https://github.com/nodejs/Release for the current NodeJS LTS Releases

8.x is a pretty safe bet.

I've got a few pulls open to clean stuff up all over the place.

**Comment by pollodigomma** [comment]
Tried to install today on node 8.12.0 and 10.0.0 . A similar error is still popping up:
[2018-10-01T09_23_27_035Z-debug.log](https://github.com/turtlecoin/turtle-pool/files/2433423/2018-10-01T09_23_27_035Z-debug.log)

**Comment by pollodigomma** [comment]
Thank you, tomorrow I'll try locally and then schedule a reboot for the pool.
