### ISSUE TITLE
Error with Cryptonote-util 

### ISSUE THREAD

**Issue by Franzferdinan51** [turtlecoin/turtle-pool#43]
Error: Cannot find module 'cryptonote-util'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/turtlepool/lib/pool.js:8:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
2018-10-06 13:03:17 [master] Pool fork 7 died, spawning replacement worker...
2018-10-06 13:03:17 [master] Pool fork 8 died, spawning replacement worker...

**Comment by yamiM0NSTER** [comment]
Be more descriptive. What environment are you trying to run pool in?

**Comment by yamiM0NSTER** [comment]
did you run ``npm update`` before trying to start pool? it should automatically download and build any needed modules.

**Comment by Franzferdinan51** [comment]
i tried that but ive come to the conclusion i may have got the wrong version of NodeJS
can u point me in the direction of the proper one please!

**Comment by RocksteadyTC** [comment]
Please use NVM https://github.com/creationix/nvm

**Comment by Franzferdinan51** [comment]
> Please use NVM https://github.com/creationix/nvm

tyvm ill look into this here in a few gotta go to work atm but when i get home my goal is to get this up and running

**Comment by yamiM0NSTER** [comment]
As far as I know there shouldn't be problems with any node version.

You can check your NodeJS version with

> node version

Also you can try this to install the module by hand:

> npm i --save git://github.com/turtlecoin/node-cryptonote-util.git

**Comment by Franzferdinan51** [comment]
node --version
v8.12.0
thats what im on ATM but i dont think i have NVM like Rocksteady had mentioned headed out now though ill return to this tonight and try what you all have mentioned

**Comment by yamiM0NSTER** [comment]
If you have 8.12 then it's not node version issue.

**Comment by Franzferdinan51** [comment]
damn i was afraid of that

**Comment by yamiM0NSTER** [comment]
Try the command to install module by hand that is above and see if there are any errors.

**Comment by brandonlehmann** [comment]
This is a module naming issue -- because I like changing names... it will be resolved shortly.

**Comment by brandonlehmann** [comment]
Please try the latest release https://github.com/turtlecoin/turtle-pool/releases/tag/v0.0.5
