### ISSUE TITLE
API wont load

### ISSUE THREAD

**Issue by Franzferdinan51** [turtlecoin/turtle-pool#47]
cant get API to load for my own coin that i forked all that happens is spinning circle tried everything im not shure what i need to post that might help me solve this issue so if u can give me a starting point i will do what i can :)

**Comment by Watt3r** [comment]
Open the dev console and see what error you are getting

**Comment by Franzferdinan51** [comment]
actually i fixxed it closing issue im a fumble fingers is what happend

**Comment by Franzferdinan51** [comment]
ty :dancer:

**Comment by Watt3r** [comment]
Can you say what fixed it in case others are getting the same issue?

**Comment by brandonlehmann** [comment]
IIRC there are only stats once someone starts mining but I could be wrong.

**Comment by brandonlehmann** [comment]
Which causes it to spin IIRC
